server:
  port: 8080

spring:
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: git@github.com:And200/project-microservices.git
          searchPaths: config-data
          passphrase: nosredna20022
          private-key: |
                        -----BEGIN OPENSSH PRIVATE KEY-----
                        b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCCUGXqLX
                        GT8N9lPhSA9s6oAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAID97CqknJyM9Z8/o
                        QD3H8JDT9llpQ1wO496NwhuSreO4AAAAoPuLyiiY+I7r9lS715SU2Uk4OLSYWq7M1h5ttw
                        yQL71Dgyvzh3aGfB5Td/LeBD+uCpeczYOU3N43+0zVM0q8cIMcuzo290rztfnTH3TIegNV
                        64nSQUFk/pRPBXm/TZW2LoFB2L0DsZqnJOKDPzmQc0RsW+6i5qMgXpOPJ8Qq9vxqg9xfFz
                        KQJQMjsetwrGZO+HUj3Rr6XBaxwBqYn/B5OHs=
                        -----END OPENSSH PRIVATE KEY-----
  security:
    user:
      name: root
      password: s3cr3t