server:
  port: 8080

spring:
  cloud:
    config:
      name: customer-service
      server:
        default-label: main
        git:
          uri: https://github.com/And200/project-microservices.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t