server:
  port: 8080

spring:
  cloud:
    config:
      server:
        default-label: main
        git:
          ignore-local-ssh-settings: true
          uri: git@github.com:And200/project-microservices.git
          searchPaths: config-data
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t