server:
  port: 8080

spring:
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/And200/project-microservices.git
          searchPaths: config-data
          username: And200
          password: nosredna20022
  security:
    user:
      name: root
      password: s3cr3t