server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-resource/customers/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products-resource/products/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/invoice-resource/items/**