spring:
  application:
    name: customer-service
  cloud:
    config:
      uri: http://localhost:8080/config-server
      username: root
      password: s3cr3t
  config:
    import: optional:configserver:http://localhost:8080