spring:
  application:
    name: customer-service
  cloud:
    config:
      uri: http://localhost:8091
      username: root
      password: s3cr3t
      enabled: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver

  sql:
    init:
      platform: h2
      username:
      password:

#JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
    defer-datasource-initialization: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false