server:
  port: 8080
  
spring:
  cloud:
    config:
      server:
         git:
          uri: https://github.com/And200/project-microservices.git
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t     